### PR TITLE
Escape quotes in autocomplete values

### LINKED ISSUE #138: Searching doesn't work when using auto completed items that have quotes

### PR DESCRIPTION
**Pull request by domcleal**
Fixes #138

### CODE REVIEW

File: lib/scoped_search/auto_complete_builder.rb [hunk 1]
```diff
@@ -208,7 +208,7 @@ def complete_value
         .uniq
         .map(&field.field)
         .compact
-        .map { |v| v.to_s =~ /\s/ ? "\"#{v}\"" : v }
+        .map { |v| v.to_s =~ /\s/ ? "\"#{v.gsub('"', '\"')}\"" : v }
```
Comment (wvanbergen) [inline lib/scoped_search/auto_complete_builder.rb]: I wonder if there is no escape/quote method we can call, instead of doing the escaping manually?

**Comment by wvanbergen** [comment]
Just one question, but thanks for looking into this and fixing!

File: lib/scoped_search/auto_complete_builder.rb (hunk 1 above)
Comment (domcleal) [inline lib/scoped_search/auto_complete_builder.rb]: The only one that comes to mind is AR's quoting for table/column names etc, but since the tokenizer is in scoped_search itself and only supports double quotes, I think gsub's going to be best.

Comment (wvanbergen) [inline lib/scoped_search/auto_complete_builder.rb]: :+1:
