### PR TITLE
STI support: searching on subclasses, parent definition inheritance

### LINKED ISSUE #112: V3.0 single table inheritance fails
I have the following query on a model with single table inheritance (EmailAssignment is a subclass of MessageAssignment)
EmailAssignment.search_for(nil).page(1)

Version 2.7.1 worked fine generating the following query:
EmailAssignment Load (0.6ms)  SELECT  "message_assignments".\* FROM "message_assignments"  WHERE "message_assignments"."type" IN ('EmailAssignment')  ORDER BY id DESC LIMIT 24 OFFSET 0

Version 3.0 however generates the following query which returns unwanted results.
MessageAssignment Load (0.7ms)  SELECT  "message_assignments".\* FROM "message_assignments"   ORDER BY id DESC LIMIT 24 OFFSET 0

### LINKED ISSUE #135: Using search in STI for both base and child class causes errors
I defined a base class and a child class and used most of the scoped_search definitions in the base class since they where relevant for all children.
I have a `belongs_to` definition in the child (it's not mentioned in the parent) and I added:
` scoped_search :in => ASSOCIATION, :on => :name, :complete_value => true, :rename => name`
in the child.
Trying to search/order by the child's association resulted in the error:
undefined method `klass' for nil:NilClass

part of the stach trace:
scoped_search (3.2.2) lib/scoped_search/definition.rb:62:in `klass'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:299:in `to_sql'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:98:in `order_by'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:533:in `order_by'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:66:in `build_find_params'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:22:in `build_query'
scoped_search (3.2.2) lib/scoped_search/definition.rb:255:in `block in register_named_scope!'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `call'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `block (2 levels) in scope'
activerecord (3.2.21) lib/active_record/scoping/default.rb:41:in `block in unscoped'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `block in scoping'
activerecord (3.2.21) lib/active_record/scoping.rb:98:in `with_scope'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `scoping'
activerecord (3.2.21) lib/active_record/scoping/default.rb:41:in `unscoped'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `block in scope'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:14:in `block in search_for'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `block in scoping'
activerecord (3.2.21) lib/active_record/scoping.rb:98:in `with_scope'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `scoping'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:14:in `search_for'

### PR DESCRIPTION
**Pull request by domcleal**
Two distinct fixes to add Single Table Inheritance (STI) support:

---

**Use current class from scope when searching, not the definition class**

With an STI parent and subclass, calling `Parent.where` within a named
scope (i.e. `search_for`) in Rails 5+ now correctly returns all parent
and subclass records. When calling `Subclass.search_for`, this would
return unexpected results from other subclasses.

Querying the class that the scope was called on ensures the result is
limited to that class, restoring very basic STI support.

Fixes #112

---

**Definitions inherit fields from STI parent class too**

When `scoped_search` is called on a parent and then its subclass, a new
`Definition` will be created and stored on the subclass that inherits
and merges fields with its parent.

The named scope will only be registered on the parent, but the most
specific definition from the subclass is used when the scope is called.
This allows `Subclass.search_for` to support both parent and subclass
fields, but `Parent.search_for` to only support parent fields.

Previously fields registered on the subclass may have used the parent's
definition causing errors finding relations as the wrong class was used.

Only works with STI parents/subclasses, not regular inheritance or
abstract classes as table and column information can safely be retrieved
against either the parent or subclass with STI.

Fixes #135

---

I have a further fix to support inheritance with abstract classes, but it was more complex with more refactoring required so I'll submit that after this has been completed.

### CODE REVIEW

**Comment by domcleal** [comment]
@wvanbergen (or another maintainer) do you have time to review this, or are you OK with me merging open PRs?

**Comment by domcleal** [comment]
PR rebased to run tests on AR 5.1 too, passing.

**Comment by wvanbergen** [comment]
I'll try to take a look at this later today, so we can merge this and do a new release.

**Comment by domcleal** [comment]
Thanks @wvanbergen.

File: spec/integration/api_spec.rb [hunk 1]
```diff
@@ -44,8 +44,22 @@
...
+
+    it "should return a ActiveRecord::Relation instance with two arguments" do
+      @class.search_for('query', {}).should be_a(ActiveRecord::Relation)
+    end
+
+    it "should respect existing scope" do
+      @class.create! field: 'a'
+      record = @class.create! field: 'ab'
+      @class.where(field: 'ab').search_for('field ~ a').should eq([record])
+    end
```
Comment (domcleal) [inline spec/integration/api_spec.rb]: Thanks, I see your point. I've moved it into a new scope_spec.rb file and updated the PR.
